name: Build Unsigned APK

on:
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  build-unsigned-apk:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Node.js 22 LTS
    - name: Setup Node.js 22 LTS
      uses: actions/setup-node@v3
      with:
        node-version: 22
        check-lts: true

    # Install Rust
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # Install Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Setup Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # Setup Android NDK
    - uses: nttld/setup-ndk@v1.5.0
      id: setup-ndk
      with:
        ndk-version: r27c

    - name: Set Env vars
      run: |
        export PATH="$PATH:$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin"
        export CMAKE_ANDROID_NDK=$NDK_HOME
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - run: npm install
    - run: rustup target add aarch64-linux-android
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - run: npm run tauri android build -- --apk
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}